runtime: java11
instance_class: F2

handlers:
  - url: /
    static_files: src/main/resources/static/login.html
    upload: src/main/resources/static/login.html

  - url: /(.*)
    static_files: src/main/resources/static/\1
    upload: src/main/resources/static/(.*)